# Generated by Django 2.1.7 on 2019-03-09 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Date',
            new_name='fFillQuestionnaire',
        ),
        migrations.DeleteModel(
            name='Day',
        ),
        migrations.DeleteModel(
            name='Month',
        ),
    ]
