# Generated by Django 2.1.7 on 2019-03-10 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0002_auto_20190309_2030'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilledQuestionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fill_date', models.DateTimeField(verbose_name='Date Submitted')),
                ('month', models.CharField(max_length=1, verbose_name='favourite month')),
                ('day', models.CharField(max_length=1, verbose_name='favourite day')),
            ],
        ),
        migrations.DeleteModel(
            name='fFillQuestionnaire',
        ),
    ]
