# Generated by Django 2.1.7 on 2019-03-11 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0004_auto_20190310_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filledquestionnaire',
            name='fill_date',
        ),
        migrations.AlterField(
            model_name='filledquestionnaire',
            name='month',
            field=models.CharField(choices=[('1', 'January'), ('2', 'February'), ('3', 'March'), ('4', 'April'), ('5', 'May'), ('6', 'June'), ('7', 'July'), ('8', 'August'), ('9', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')], max_length=2, verbose_name='favourite month'),
        ),
    ]
